#include "HeadPhone.h"




String HeadPhone::getManufacturer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:000000000000097D begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:000000000000097D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer HeadPhone::getYear()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:000000000000097F begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:000000000000097F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer HeadPhone::getMagnetSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:000000000000098C begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:000000000000098C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

String HeadPhone::getModelName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BC0 begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BC0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

HeadPhone::HeadPhone(String manufact, String name, Integer makeYear, Integer magnet)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BD7 begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BD7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
