#include "HeadPhoneManufacturer.h"




HeadPhoneManufacturer::HeadPhoneManufacturer(String name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BCD begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BCD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void HeadPhoneManufacturer::addModel(String modelName, Integer makeYear, Integer magnetSize)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BD0 begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BD0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

HeadPhone HeadPhoneManufacturer::getModel(String modelName)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BD4 begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BD4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void HeadPhoneManufacturer::deleteModel(String modelName)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BDD begin
{
}
// section 127-0-1-1-15c42932:1665859f7e9:-8000:0000000000000BDD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
